spring.datasource.url=jdbc:postgresql://dpg-d19lafripnbc7395rl2g-a.oregon-postgres.render.com/evchargerdb_essb
spring.datasource.username=nodercif
spring.datasource.password=8XOZmB3uY2IGGLsqdIgGDH0IByHgfB9k

jwt.secret=X3Fn2qI+JZ6fvEXtM9ZIb8RfJq1FxCDt1y4h7TGVRA4=